// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WildlifeConservation.Repositories.Data;

#nullable disable

namespace WildlifeConservation.Repositories.Migrations
{
    [DbContext(typeof(WildlifeDbContext))]
    [Migration("20260712124500_AddUserAssignedArea")]
    partial class AddUserAssignedArea
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
#pragma warning restore 612, 618
        }
    }
}
