// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WildlifeConservation.Repositories.Data;

#nullable disable

namespace WildlifeConservation.Repositories.Migrations
{
    [DbContext(typeof(WildlifeDbContext))]
    partial class WildlifeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WildlifeConservation.Models.Alerts.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertType")
                        .HasColumnType("integer");

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<int?>("CollarId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("CollarId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Alerts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlertType = 1,
                            AnimalId = 1,
                            CollarId = 1,
                            CreatedAt = new DateTime(2026, 1, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Animal moved close to the southern reserve boundary.",
                            IsResolved = false,
                            Severity = 2
                        },
                        new
                        {
                            Id = 2,
                            AlertType = 2,
                            AnimalId = 3,
                            CollarId = 3,
                            CreatedAt = new DateTime(2026, 1, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Collar battery is below threshold.",
                            IsResolved = false,
                            Severity = 1
                        },
                        new
                        {
                            Id = 3,
                            AlertType = 4,
                            AnimalId = 4,
                            CollarId = 4,
                            CreatedAt = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Manual watch requested after boundary movement.",
                            IsResolved = true,
                            ResolvedAt = new DateTime(2026, 1, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Severity = 1
                        },
                        new
                        {
                            Id = 4,
                            AlertType = 5,
                            AnimalId = 5,
                            CreatedAt = new DateTime(2026, 1, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 2,
                            Description = "Review relocation zone condition after ranger report.",
                            IsResolved = false,
                            Severity = 0
                        });
                });

            modelBuilder.Entity("WildlifeConservation.Models.Animals.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SubspeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubspeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2014, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Amara",
                            Notes = "Matriarch of a small herd.",
                            Sex = 2,
                            SubspeciesId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2017, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Kito",
                            Notes = "Often seen near the western watering route.",
                            Sex = 1,
                            SubspeciesId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2019, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sera",
                            Notes = "Adult lioness in northern pride.",
                            Sex = 2,
                            SubspeciesId = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Batu",
                            Notes = "Dispersing male observed near reserve edge.",
                            Sex = 1,
                            SubspeciesId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2016, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Nila",
                            Notes = "Relocated after crop-raiding incident.",
                            Sex = 2,
                            SubspeciesId = 2
                        });
                });

            modelBuilder.Entity("WildlifeConservation.Models.CollarAssignments.CollarAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CollarId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId")
                        .IsUnique()
                        .HasFilter("\"UnassignedAt\" IS NULL");

                    b.HasIndex("CollarId")
                        .IsUnique()
                        .HasFilter("\"UnassignedAt\" IS NULL");

                    b.ToTable("CollarAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = 1,
                            AssignedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CollarId = 1,
                            Notes = "Initial collaring during health check."
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = 2,
                            AssignedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CollarId = 2,
                            Notes = "Assigned after herd survey."
                        },
                        new
                        {
                            Id = 3,
                            AnimalId = 3,
                            AssignedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CollarId = 3,
                            Notes = "Assigned near northern pride range."
                        },
                        new
                        {
                            Id = 4,
                            AnimalId = 4,
                            AssignedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CollarId = 4,
                            Notes = "Assigned near reserve boundary."
                        },
                        new
                        {
                            Id = 5,
                            AnimalId = 5,
                            AssignedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CollarId = 5,
                            Notes = "Assigned after relocation release."
                        });
                });

            modelBuilder.Entity("WildlifeConservation.Models.Collars.Collar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Model")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Collars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "EcoTelemetry",
                            Model = "SavannaTrack X1",
                            Notes = "Solar-assisted battery pack.",
                            SerialNumber = "WC-GPS-1001",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "EcoTelemetry",
                            Model = "SavannaTrack X1",
                            Notes = "Configured for elephant migration interval.",
                            SerialNumber = "WC-GPS-1002",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "RangeSense",
                            Model = "PredatorLink P4",
                            Notes = "High-frequency predator tracking.",
                            SerialNumber = "WC-GPS-2001",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "RangeSense",
                            Model = "CanidTrail C2",
                            Notes = "Cold-weather battery profile.",
                            SerialNumber = "WC-GPS-3001",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Manufacturer = "EcoTelemetry",
                            Model = "ForestTrack F2",
                            Notes = "Dense canopy satellite profile.",
                            SerialNumber = "WC-GPS-1003",
                            Status = 1
                        });
                });

            modelBuilder.Entity("WildlifeConservation.Models.LocationPoints.LocationPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Altitude")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<int>("CollarId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SignalType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId", "RecordedAt");

                    b.HasIndex("CollarId", "RecordedAt");

                    b.ToTable("LocationPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Altitude = 1524.50m,
                            AnimalId = 1,
                            CollarId = 1,
                            Latitude = -1.942345m,
                            Longitude = 35.148900m,
                            Notes = "Near southern water point.",
                            RecordedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            SignalType = 1
                        },
                        new
                        {
                            Id = 2,
                            Altitude = 1527.10m,
                            AnimalId = 1,
                            CollarId = 1,
                            Latitude = -1.935120m,
                            Longitude = 35.153420m,
                            RecordedAt = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            SignalType = 1
                        },
                        new
                        {
                            Id = 3,
                            Altitude = 1495.00m,
                            AnimalId = 2,
                            CollarId = 2,
                            Latitude = -1.851100m,
                            Longitude = 35.221200m,
                            RecordedAt = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            SignalType = 0
                        },
                        new
                        {
                            Id = 4,
                            Altitude = 1492.20m,
                            AnimalId = 2,
                            CollarId = 2,
                            Latitude = -1.844980m,
                            Longitude = 35.229310m,
                            Notes = "Moving east.",
                            RecordedAt = new DateTime(2026, 1, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            SignalType = 0
                        },
                        new
                        {
                            Id = 5,
                            Altitude = 1411.00m,
                            AnimalId = 3,
                            CollarId = 3,
                            Latitude = -1.712420m,
                            Longitude = 35.012780m,
                            Notes = "Northern pride range.",
                            RecordedAt = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            SignalType = 1
                        },
                        new
                        {
                            Id = 6,
                            Altitude = 1409.30m,
                            AnimalId = 3,
                            CollarId = 3,
                            Latitude = -1.708700m,
                            Longitude = 35.018050m,
                            RecordedAt = new DateTime(2026, 1, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            SignalType = 1
                        },
                        new
                        {
                            Id = 7,
                            Altitude = 864.00m,
                            AnimalId = 4,
                            CollarId = 4,
                            Latitude = 44.138700m,
                            Longitude = 20.458100m,
                            Notes = "Boundary corridor.",
                            RecordedAt = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            SignalType = 2
                        },
                        new
                        {
                            Id = 8,
                            Altitude = 872.30m,
                            AnimalId = 4,
                            CollarId = 4,
                            Latitude = 44.142900m,
                            Longitude = 20.462450m,
                            RecordedAt = new DateTime(2026, 1, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            SignalType = 2
                        },
                        new
                        {
                            Id = 9,
                            Altitude = 912.00m,
                            AnimalId = 5,
                            CollarId = 5,
                            Latitude = 11.551200m,
                            Longitude = 76.231500m,
                            Notes = "Post-release forest range.",
                            RecordedAt = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            SignalType = 1
                        },
                        new
                        {
                            Id = 10,
                            Altitude = 918.80m,
                            AnimalId = 5,
                            CollarId = 5,
                            Latitude = 11.557400m,
                            Longitude = 76.236100m,
                            RecordedAt = new DateTime(2026, 1, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            SignalType = 1
                        });
                });

            modelBuilder.Entity("WildlifeConservation.Models.RangerReports.RangerReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<int>("ReportType")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("UserId");

                    b.ToTable("RangerReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Herd sighted moving calmly toward grazing area.",
                            Latitude = -1.935000m,
                            Longitude = 35.153000m,
                            ReportType = 0,
                            Severity = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = 3,
                            CreatedAt = new DateTime(2026, 1, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Collar antenna appears tilted but still reporting.",
                            Latitude = -1.708500m,
                            Longitude = 35.018000m,
                            ReportType = 2,
                            Severity = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 11, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh snares found along dry stream bed.",
                            Latitude = -1.774000m,
                            Longitude = 35.097000m,
                            ReportType = 3,
                            Severity = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            AnimalId = 4,
                            CreatedAt = new DateTime(2026, 1, 11, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tracks and visual confirmation near corridor camera.",
                            Latitude = 44.142800m,
                            Longitude = 20.462300m,
                            ReportType = 0,
                            Severity = 0,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("WildlifeConservation.Models.Species.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Large herbivorous mammals monitored for migration and habitat pressure.",
                            Name = "Elephant"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Large carnivores monitored for pride movement and human-wildlife conflict.",
                            Name = "Lion"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Social carnivores monitored for range behavior and conservation planning.",
                            Name = "Wolf"
                        });
                });

            modelBuilder.Entity("WildlifeConservation.Models.Subspecies.Subspecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId", "Name")
                        .IsUnique();

                    b.ToTable("Subspecies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Open savanna elephant population.",
                            Name = "African Savanna Elephant",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Forest and grassland elephant population.",
                            Name = "Asian Elephant",
                            SpeciesId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lion population tracked across protected ranges.",
                            Name = "East African Lion",
                            SpeciesId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Wolf population monitored near reserve corridors.",
                            Name = "Eurasian Wolf",
                            SpeciesId = 3
                        });
                });

            modelBuilder.Entity("WildlifeConservation.Models.Users.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 0,
                            Description = "View animals."
                        },
                        new
                        {
                            Id = 2,
                            Code = 1,
                            Description = "Create and update animals."
                        },
                        new
                        {
                            Id = 3,
                            Code = 2,
                            Description = "View alerts."
                        },
                        new
                        {
                            Id = 4,
                            Code = 3,
                            Description = "Create and update alerts."
                        },
                        new
                        {
                            Id = 5,
                            Code = 4,
                            Description = "View collars."
                        },
                        new
                        {
                            Id = 6,
                            Code = 5,
                            Description = "Create and update collars."
                        },
                        new
                        {
                            Id = 7,
                            Code = 6,
                            Description = "View collar assignments."
                        },
                        new
                        {
                            Id = 8,
                            Code = 7,
                            Description = "Create and update collar assignments."
                        },
                        new
                        {
                            Id = 9,
                            Code = 8,
                            Description = "View location points."
                        },
                        new
                        {
                            Id = 10,
                            Code = 9,
                            Description = "Create and update location points."
                        },
                        new
                        {
                            Id = 11,
                            Code = 10,
                            Description = "View ranger reports."
                        },
                        new
                        {
                            Id = 12,
                            Code = 11,
                            Description = "Create and update ranger reports."
                        },
                        new
                        {
                            Id = 13,
                            Code = 12,
                            Description = "View species."
                        },
                        new
                        {
                            Id = 14,
                            Code = 13,
                            Description = "Create and update species."
                        },
                        new
                        {
                            Id = 15,
                            Code = 14,
                            Description = "View subspecies."
                        },
                        new
                        {
                            Id = 16,
                            Code = 15,
                            Description = "Create and update subspecies."
                        },
                        new
                        {
                            Id = 17,
                            Code = 16,
                            Description = "View users."
                        },
                        new
                        {
                            Id = 18,
                            Code = 17,
                            Description = "Create and update users."
                        },
                        new
                        {
                            Id = 19,
                            Code = 18,
                            Description = "View roles."
                        },
                        new
                        {
                            Id = 20,
                            Code = 19,
                            Description = "Create and update roles."
                        },
                        new
                        {
                            Id = 21,
                            Code = 20,
                            Description = "Unrestricted platform access."
                        });
                });

            modelBuilder.Entity("WildlifeConservation.Models.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Field staff who record and maintain conservation data.",
                            Name = "Ranger"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Read-only access to conservation data.",
                            Name = "Researcher"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Platform administration and conservation data management.",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Unrestricted platform administration.",
                            Name = "Master"
                        });
                });

            modelBuilder.Entity("WildlifeConservation.Models.Users.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 21
                        });
                });

            modelBuilder.Entity("WildlifeConservation.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AssignedLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("AssignedLocationName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal?>("AssignedLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<int?>("AssignedMapZoom")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "maya.ranger@example.org",
                            FullName = "Maya Nkosi",
                            IsActive = true,
                            PasswordHash = "lqAUSV0CyDeazcHyVWUyWOaBpl2tKJEcNMt8NLu6OmY=",
                            PasswordSalt = "UmFuZ2VyU2VlZFNhbHQxMjM="
                        },
                        new
                        {
                            Id = 2,
                            Email = "luka.research@example.org",
                            FullName = "Luka Petrovic",
                            IsActive = true,
                            PasswordHash = "BeTAbhUpC/HalIdpn4pENMoRhM6MTo8l1G0pP/IqoqI=",
                            PasswordSalt = "UmVzZWFyY2hTZWVkU2FsdDE="
                        },
                        new
                        {
                            Id = 3,
                            Email = "anika.admin@example.org",
                            FullName = "Anika Rao",
                            IsActive = true,
                            PasswordHash = "S17Qn4Xrpy+dcZCVD5zuHuq4t32wjdBDGTSMzxjSDLY=",
                            PasswordSalt = "QWRtaW5TZWVkU2FsdDEyMw=="
                        },
                        new
                        {
                            Id = 4,
                            Email = "elena.master@example.org",
                            FullName = "Elena Markovic",
                            IsActive = true,
                            PasswordHash = "0dGX1Bj3IhmZb191BWpw4+oNtT3ldhTzq1qJTlcRj9k=",
                            PasswordSalt = "TWFzdGVyU2VlZFNhbHQxMjM="
                        });
                });

            modelBuilder.Entity("WildlifeConservation.Models.Users.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("WildlifeConservation.Models.Alerts.Alert", b =>
                {
                    b.HasOne("WildlifeConservation.Models.Animals.Animal", "Animal")
                        .WithMany("Alerts")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WildlifeConservation.Models.Collars.Collar", "Collar")
                        .WithMany("Alerts")
                        .HasForeignKey("CollarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WildlifeConservation.Models.Users.User", "CreatedByUser")
                        .WithMany("Alerts")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Animal");

                    b.Navigation("Collar");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("WildlifeConservation.Models.Animals.Animal", b =>
                {
                    b.HasOne("WildlifeConservation.Models.Subspecies.Subspecies", "Subspecies")
                        .WithMany("Animals")
                        .HasForeignKey("SubspeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subspecies");
                });

            modelBuilder.Entity("WildlifeConservation.Models.CollarAssignments.CollarAssignment", b =>
                {
                    b.HasOne("WildlifeConservation.Models.Animals.Animal", "Animal")
                        .WithMany("CollarAssignments")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WildlifeConservation.Models.Collars.Collar", "Collar")
                        .WithMany("CollarAssignments")
                        .HasForeignKey("CollarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Collar");
                });

            modelBuilder.Entity("WildlifeConservation.Models.LocationPoints.LocationPoint", b =>
                {
                    b.HasOne("WildlifeConservation.Models.Animals.Animal", "Animal")
                        .WithMany("LocationPoints")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WildlifeConservation.Models.Collars.Collar", "Collar")
                        .WithMany("LocationPoints")
                        .HasForeignKey("CollarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Collar");
                });

            modelBuilder.Entity("WildlifeConservation.Models.RangerReports.RangerReport", b =>
                {
                    b.HasOne("WildlifeConservation.Models.Animals.Animal", "Animal")
                        .WithMany("RangerReports")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WildlifeConservation.Models.Users.User", "User")
                        .WithMany("RangerReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WildlifeConservation.Models.Subspecies.Subspecies", b =>
                {
                    b.HasOne("WildlifeConservation.Models.Species.Species", "Species")
                        .WithMany("Subspecies")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("WildlifeConservation.Models.Users.RolePermission", b =>
                {
                    b.HasOne("WildlifeConservation.Models.Users.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WildlifeConservation.Models.Users.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WildlifeConservation.Models.Users.UserRole", b =>
                {
                    b.HasOne("WildlifeConservation.Models.Users.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WildlifeConservation.Models.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WildlifeConservation.Models.Animals.Animal", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("CollarAssignments");

                    b.Navigation("LocationPoints");

                    b.Navigation("RangerReports");
                });

            modelBuilder.Entity("WildlifeConservation.Models.Collars.Collar", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("CollarAssignments");

                    b.Navigation("LocationPoints");
                });

            modelBuilder.Entity("WildlifeConservation.Models.Species.Species", b =>
                {
                    b.Navigation("Subspecies");
                });

            modelBuilder.Entity("WildlifeConservation.Models.Subspecies.Subspecies", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("WildlifeConservation.Models.Users.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("WildlifeConservation.Models.Users.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WildlifeConservation.Models.Users.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("RangerReports");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
