<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WildlifeConservation.Api\WildlifeConservation.Api.csproj" />
    <ProjectReference Include="..\WildlifeConservation.Services\WildlifeConservation.Services.csproj" />
    <ProjectReference Include="..\WildlifeConservation.Repositories\WildlifeConservation.Repositories.csproj" />
    <ProjectReference Include="..\WildlifeConservation.Models\WildlifeConservation.Models.csproj" />
    <ProjectReference Include="..\WildlifeConservation.DTOs\WildlifeConservation.DTOs.csproj" />
    <ProjectReference Include="..\WildlifeConservation.Shared\WildlifeConservation.Shared.csproj" />
  </ItemGroup>

</Project>
